# Form implementation generated from reading ui file 'anewBecker.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 168)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"color:#fff;\n"
"font:11pt \"Helvetica\";\n"
"}\n"
"\n"
"QLabel {\n"
"background:transparent;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"                                 QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgba(22,22,22,100);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/*\n"
"VERTICAL\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:vertical {\n"
"    border-radius: 11px;\n"
"    width: 22px;\n"
"    margin: 0px;\n"
"    background-color: rgba(33,33,33,100);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgba(44,44,44,100);    \n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 22px;\n"
"    width: 22px;\n"
"    margin: 0px;\n"
"    border-radius: 11px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:transparent;\n"
"    height: 12px;\n"
"    margin: 0px 10px 0px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(22,22,22);\n"
"    min-width:24px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, \n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    width: 12px;\n"
"    margin: 10px 0px 10px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(22,22,22);\n"
"    min-height: 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"background-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainpanePage1 = QtWidgets.QWidget()
        self.mainpanePage1.setObjectName("mainpanePage1")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.mainpanePage1)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.mainpanePage1)
        self.tabWidget.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QToolTip\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QToolTip {\n"
"        background: rgba(23,23,23, 150);\n"
"        border: 1px solid rgb(100,199,211);\n"
"        border-radius: 5px;\n"
"        padding:4px;\n"
"        text-align: left;\n"
"        color: rgb(100,199,211);\n"
"    }\n"
"    \n"
"QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"margin-left:3px;\n"
"padding-top:2px;\n"
"padding-bottom:2px;\n"
"background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"font-weight:bold;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.tabWidget.setIconSize(QtCore.QSize(12, 12))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.sadness = QtWidgets.QSlider(parent=self.frame_4)
        self.sadness.setMinimumSize(QtCore.QSize(45, 0))
        self.sadness.setMaximumSize(QtCore.QSize(16777215, 90))
        self.sadness.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(87,111,215);}\n"
"QSlider::handle:vertical:hover {background:rgb(127,151,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(37,61,165);}\n"
"QSlider::groove:vertical:hover {background:rgba(87,111,215,0.25);}\n"
"QSlider::groove:vertical {background:rgba(87,111,215,0.15);}\n"
"\n"
"        ")
        self.sadness.setMaximum(3)
        self.sadness.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sadness.setInvertedAppearance(True)
        self.sadness.setObjectName("sadness")
        self.gridLayout_14.addWidget(self.sadness, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_15.setStyleSheet("")
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/basicsblue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.tab_2)
        self.frame.setObjectName("frame")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.victimhood = QtWidgets.QSlider(parent=self.frame)
        self.victimhood.setMinimumSize(QtCore.QSize(45, 0))
        self.victimhood.setMaximumSize(QtCore.QSize(16777215, 90))
        self.victimhood.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(153,153,255);}\n"
"QSlider::handle:vertical:hover {background:rgb(193,193,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(103,103,205);}\n"
"QSlider::groove:vertical:hover {background:rgba(153,153,255,0.25);}\n"
"QSlider::groove:vertical {background:rgba(153,153,255,0.15);}\n"
"\n"
"        ")
        self.victimhood.setMaximum(3)
        self.victimhood.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.victimhood.setInvertedAppearance(True)
        self.victimhood.setObjectName("victimhood")
        self.gridLayout_13.addWidget(self.victimhood, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setStyleSheet("")
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/1 4.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame1 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame1.setObjectName("frame1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_12 = QtWidgets.QLabel(parent=self.frame1)
        self.label_12.setStyleSheet("")
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 1, 1, 1)
        self.pessimism = QtWidgets.QSlider(parent=self.frame1)
        self.pessimism.setMinimumSize(QtCore.QSize(45, 0))
        self.pessimism.setMaximumSize(QtCore.QSize(16777215, 90))
        self.pessimism.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(214,157,210);}\n"
"QSlider::handle:vertical:hover {background:rgb(254,197,250);}\n"
"QSlider::handle:vertical:pressed {background:rgb(164,107,160);}\n"
"QSlider::groove:vertical:hover {background:rgba(214,157,210,0.25);}\n"
"QSlider::groove:vertical {background:rgba(214,157,210,0.15);}\n"
"\n"
"        ")
        self.pessimism.setMaximum(3)
        self.pessimism.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.pessimism.setInvertedAppearance(True)
        self.pessimism.setObjectName("pessimism")
        self.gridLayout_7.addWidget(self.pessimism, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame1, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/asfdasfasdfasdf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_19.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_5 = QtWidgets.QFrame(parent=self.tab_6)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_16.setStyleSheet("")
        self.label_16.setWordWrap(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 0, 1, 1, 1)
        self.interest = QtWidgets.QSlider(parent=self.frame_5)
        self.interest.setMinimumSize(QtCore.QSize(45, 0))
        self.interest.setMaximumSize(QtCore.QSize(16777215, 90))
        self.interest.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(247,198,94);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,238,134);}\n"
"QSlider::handle:vertical:pressed {background:rgb(197,148,44);}\n"
"QSlider::groove:vertical:hover {background:rgba(247,198,94,0.25);}\n"
"QSlider::groove:vertical {background:rgba(247,198,94,0.15);}\n"
"\n"
"        ")
        self.interest.setMaximum(3)
        self.interest.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.interest.setInvertedAppearance(True)
        self.interest.setObjectName("interest")
        self.gridLayout_8.addWidget(self.interest, 0, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_5, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/effort.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_6, icon3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_18.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_6 = QtWidgets.QFrame(parent=self.tab_7)
        self.frame_6.setMinimumSize(QtCore.QSize(45, 0))
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_17.setStyleSheet("")
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 0, 1, 1, 1)
        self.effort = QtWidgets.QSlider(parent=self.frame_6)
        self.effort.setMinimumSize(QtCore.QSize(45, 0))
        self.effort.setMaximumSize(QtCore.QSize(16777215, 90))
        self.effort.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(255,89,156);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,129,196);}\n"
"QSlider::handle:vertical:pressed {background:rgb(205,39,106);}\n"
"QSlider::groove:vertical:hover {background:rgba(255,89,156,0.25);}\n"
"QSlider::groove:vertical {background:rgba(255,89,156,0.15);}\n"
"\n"
"        ")
        self.effort.setMaximum(3)
        self.effort.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.effort.setInvertedAppearance(True)
        self.effort.setObjectName("effort")
        self.gridLayout_9.addWidget(self.effort, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.frame_6, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/libidoHole.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_7, icon4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_7 = QtWidgets.QFrame(parent=self.tab_8)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.decisiveness = QtWidgets.QSlider(parent=self.frame_7)
        self.decisiveness.setMinimumSize(QtCore.QSize(45, 0))
        self.decisiveness.setMaximumSize(QtCore.QSize(16777215, 90))
        self.decisiveness.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(120,155,172);}\n"
"QSlider::handle:vertical:hover {background:rgb(160,195,212);}\n"
"QSlider::handle:vertical:pressed {background:rgb(70,105,122);}\n"
"QSlider::groove:vertical:hover {background:rgba(120,155,172,0.25);}\n"
"QSlider::groove:vertical {background:rgba(120,155,172,0.15);}\n"
"\n"
"        ")
        self.decisiveness.setMaximum(3)
        self.decisiveness.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.decisiveness.setInvertedAppearance(True)
        self.decisiveness.setObjectName("decisiveness")
        self.gridLayout_10.addWidget(self.decisiveness, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_7, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/solitudeHole.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_8, icon5, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_9)
        self.gridLayout_17.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_8 = QtWidgets.QFrame(parent=self.tab_9)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 1, 1, 1)
        self.hygiene = QtWidgets.QSlider(parent=self.frame_8)
        self.hygiene.setMinimumSize(QtCore.QSize(45, 0))
        self.hygiene.setMaximumSize(QtCore.QSize(16777215, 90))
        self.hygiene.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(96,174,106);}\n"
"QSlider::handle:vertical:hover {background:rgb(136,214,146);}\n"
"QSlider::handle:vertical:pressed {background:rgb(46,124,56);}\n"
"QSlider::groove:vertical:hover {background:rgba(96,174,106,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(96,174,106,0.15);}\n"
"\n"
"        ")
        self.hygiene.setMaximum(3)
        self.hygiene.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.hygiene.setInvertedAppearance(True)
        self.hygiene.setObjectName("hygiene")
        self.gridLayout_11.addWidget(self.hygiene, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_8, 0, 0, 1, 1)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasdfasfsadfasf.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_9, icon6, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_9 = QtWidgets.QFrame(parent=self.tab_4)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.sexdrive = QtWidgets.QSlider(parent=self.frame_9)
        self.sexdrive.setMinimumSize(QtCore.QSize(45, 0))
        self.sexdrive.setMaximumSize(QtCore.QSize(16777215, 90))
        self.sexdrive.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(229,100,111);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,140,151);}\n"
"QSlider::handle:vertical:pressed {background:rgb(179,50,61);}\n"
"QSlider::groove:vertical:hover {background:rgba(229,100,111,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(229,100,111,0.15);}\n"
"\n"
"        ")
        self.sexdrive.setMaximum(3)
        self.sexdrive.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sexdrive.setInvertedAppearance(True)
        self.sexdrive.setObjectName("sexdrive")
        self.gridLayout_15.addWidget(self.sexdrive, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_20.setStyleSheet("")
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_9, 0, 0, 1, 1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/asdfasfasfasfas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_4, icon7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout.setContentsMargins(8, 8, 8, 8)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_10 = QtWidgets.QFrame(parent=self.tab_5)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_14.setStyleSheet("")
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.gridLayout_16.addWidget(self.label_14, 0, 1, 1, 1)
        self.solitude = QtWidgets.QSlider(parent=self.frame_10)
        self.solitude.setMinimumSize(QtCore.QSize(45, 0))
        self.solitude.setMaximumSize(QtCore.QSize(16777215, 90))
        self.solitude.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(223,133,93);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,173,133);}\n"
"QSlider::handle:vertical:pressed {background:rgb(173,83,43);}\n"
"QSlider::groove:vertical:hover {background:rgba(223,133,93,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(223,133,93,0.15);}\n"
"\n"
"        ")
        self.solitude.setMaximum(3)
        self.solitude.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.solitude.setInvertedAppearance(True)
        self.solitude.setObjectName("solitude")
        self.gridLayout_16.addWidget(self.solitude, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_10, 0, 0, 1, 1)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/Decisiveness.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_5, icon8, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout_21.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_11 = QtWidgets.QFrame(parent=self.tab_10)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.guilt = QtWidgets.QSlider(parent=self.frame_11)
        self.guilt.setMinimumSize(QtCore.QSize(45, 0))
        self.guilt.setMaximumSize(QtCore.QSize(16777215, 90))
        self.guilt.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(170,129,224);}\n"
"QSlider::handle:vertical:hover {background:rgb(210,169,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(120,79,174);}\n"
"QSlider::groove:vertical:hover {background:rgba(170,129,224,0.25);}\n"
"QSlider::groove:vertical {background:rgba(170,129,224,0.15);}\n"
"\n"
"        ")
        self.guilt.setMaximum(3)
        self.guilt.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.guilt.setInvertedAppearance(True)
        self.guilt.setObjectName("guilt")
        self.gridLayout_20.addWidget(self.guilt, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_21.setStyleSheet("")
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_20.addWidget(self.label_21, 0, 1, 1, 1)
        self.gridLayout_21.addWidget(self.frame_11, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_10, icon2, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_27.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_27.setSpacing(0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.frame_2 = QtWidgets.QFrame(parent=self.tab_12)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setSpacing(6)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_23.setStyleSheet("")
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_26.addWidget(self.label_23, 0, 1, 1, 1)
        self.sleep = QtWidgets.QSlider(parent=self.frame_2)
        self.sleep.setMinimumSize(QtCore.QSize(45, 0))
        self.sleep.setMaximumSize(QtCore.QSize(16777215, 90))
        self.sleep.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(214,157,210);}\n"
"QSlider::handle:vertical:hover {background:rgb(254,197,250);}\n"
"QSlider::handle:vertical:pressed {background:rgb(164,107,160);}\n"
"QSlider::groove:vertical:hover {background:rgba(214,157,210,0.25);}\n"
"QSlider::groove:vertical {background:rgba(214,157,210,0.15);}\n"
"\n"
"        ")
        self.sleep.setMaximum(3)
        self.sleep.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.sleep.setInvertedAppearance(True)
        self.sleep.setObjectName("sleep")
        self.gridLayout_26.addWidget(self.sleep, 0, 0, 1, 1)
        self.gridLayout_27.addWidget(self.frame_2, 0, 0, 1, 1)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/Interest.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_12, icon9, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_23.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.frame_12 = QtWidgets.QFrame(parent=self.tab_11)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_12)
        self.label_22.setStyleSheet("")
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_22.addWidget(self.label_22, 0, 1, 1, 1)
        self.outlook = QtWidgets.QSlider(parent=self.frame_12)
        self.outlook.setMinimumSize(QtCore.QSize(45, 0))
        self.outlook.setMaximumSize(QtCore.QSize(16777215, 90))
        self.outlook.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(200,129,224);}\n"
"QSlider::handle:vertical:hover {background:rgb(240,169,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(150,79,174);}\n"
"QSlider::groove:vertical:hover {background:rgba(200,129,224,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(200,129,224,0.15);}\n"
"\n"
"        ")
        self.outlook.setMaximum(3)
        self.outlook.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.outlook.setInvertedAppearance(True)
        self.outlook.setObjectName("outlook")
        self.gridLayout_22.addWidget(self.outlook, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.frame_12, 0, 0, 1, 1)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/Victimhood.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon10.addPixmap(QtGui.QPixmap(":/newPrefix/BECK EXAM/cxccxx.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.tabWidget.addTab(self.tab_11, icon10, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.tab_13)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.frame_3 = QtWidgets.QFrame(parent=self.tab_13)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setHorizontalSpacing(12)
        self.gridLayout_29.setVerticalSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.altmans_summary_label = QtWidgets.QLabel(parent=self.frame_3)
        self.altmans_summary_label.setStyleSheet("font-weight:bold;margin-top:4px; margin-bottom:4px;")
        self.altmans_summary_label.setObjectName("altmans_summary_label")
        self.gridLayout_29.addWidget(self.altmans_summary_label, 1, 1, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setObjectName("label")
        self.gridLayout_29.addWidget(self.label, 0, 1, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_30.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_30.setSpacing(0)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame_13)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 361, 150))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setSpacing(0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_31.addWidget(self.label_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_30.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.frame_13, 2, 1, 1, 2)
        self.beck_summary = QtWidgets.QSlider(parent=self.frame_3)
        self.beck_summary.setMinimumSize(QtCore.QSize(45, 90))
        self.beck_summary.setMaximumSize(QtCore.QSize(16777215, 90))
        self.beck_summary.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(244,56,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.08);}\n"
"\n"
"        ")
        self.beck_summary.setMaximum(36)
        self.beck_summary.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.beck_summary.setInvertedAppearance(True)
        self.beck_summary.setObjectName("beck_summary")
        self.gridLayout_29.addWidget(self.beck_summary, 0, 0, 3, 1)
        self.gridLayout_32.addWidget(self.frame_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_32.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_13, "")
        self.gridLayout_24.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.mainpanePage1)
        self.mainpanePage2 = QtWidgets.QWidget()
        self.mainpanePage2.setObjectName("mainpanePage2")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.mainpanePage2)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.beck_tableview = QtWidgets.QTableView(parent=self.mainpanePage2)
        self.beck_tableview.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.beck_tableview.setShowGrid(False)
        self.beck_tableview.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.beck_tableview.setSortingEnabled(True)
        self.beck_tableview.setObjectName("beck_tableview")
        self.beck_tableview.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_25.addWidget(self.beck_tableview, 1, 0, 1, 1)
        self.hidemeframe = QtWidgets.QFrame(parent=self.mainpanePage2)
        self.hidemeframe.setObjectName("hidemeframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.hidemeframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.beck_time = QtWidgets.QTimeEdit(parent=self.hidemeframe)
        self.beck_time.setObjectName("beck_time")
        self.horizontalLayout.addWidget(self.beck_time)
        self.beck_date = QtWidgets.QDateEdit(parent=self.hidemeframe)
        self.beck_date.setObjectName("beck_date")
        self.horizontalLayout.addWidget(self.beck_date)
        self.gridLayout_25.addWidget(self.hidemeframe, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.mainpanePage2)
        self.gridLayout_12.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 466, 16))
        self.menubar.setObjectName("menubar")
        self.menuBECK = QtWidgets.QMenu(parent=self.menubar)
        self.menuBECK.setObjectName("menuBECK")
        self.menuViews = QtWidgets.QMenu(parent=self.menubar)
        self.menuViews.setObjectName("menuViews")
        MainWindow.setMenuBar(self.menubar)
        self.actionCommit = QtGui.QAction(parent=MainWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.actionDelete_Record = QtGui.QAction(parent=MainWindow)
        self.actionDelete_Record.setObjectName("actionDelete_Record")
        self.actionMinimize = QtGui.QAction(parent=MainWindow)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionMaximize = QtGui.QAction(parent=MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionInput_View = QtGui.QAction(parent=MainWindow)
        self.actionInput_View.setObjectName("actionInput_View")
        self.actionDataview = QtGui.QAction(parent=MainWindow)
        self.actionDataview.setObjectName("actionDataview")
        self.menuBECK.addAction(self.actionCommit)
        self.menuBECK.addAction(self.actionDelete_Record)
        self.menuBECK.addAction(self.actionMinimize)
        self.menuBECK.addAction(self.actionMaximize)
        self.menuViews.addAction(self.actionInput_View)
        self.menuViews.addAction(self.actionDataview)
        self.menubar.addAction(self.menuBECK.menuAction())
        self.menubar.addAction(self.menuViews.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.beck_summary.valueChanged['int'].connect(self.altmans_summary_label.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>Today, I do not feel sad.</p><p>Today, I feel sad.</p><p>Today, I feel sad all the time and can\'t snap out of it.</p><p>Today, I feel so sad and unhappy that I can\'t stand it.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sadness"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p>Today, I don’t feel I am being punished.</p><p>Today, I feel I may be punished.</p><p>Today, I expect to be punished.</p><p>Today, I feel I am being punished.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "victimhood"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>I don\'t feel disappointed in myself. </p><p>I am disappointed in myself.</p><p>I am disgusted with myself.</p><p>I hate myself.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "pessimism"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Today, I get as much satisfaction out of things as I used to.</p><p>Today, I don’t enjoy things the way I used to.</p><p>Today, I don\'t get real satisfaction out of anything anymore.</p><p>Today, I am dissatisfied or bored with everything.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "interest"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Today, I can work about as well as before.</p><p>Today, it takes extra effort to get started doing something.</p><p>Today, I have to push myself very hard to do anything.</p><p>Today, I can\'t do any work at all.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "effort"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p>Today, I make decisions about as well as I ever could.</p><p>Today, I put off making decisions more than I used to.</p><p>Today, I have greater difficulty in making decisions than I used to.</p><p>Today, I can\'t make decisions at all anymore.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "decisiveness"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Today, I don’t feel that I look any worse than I used to.</p><p>Today, I am worried that I am looking old or unattractive.</p><p>Today, I am gross without redemption.</p><p>Today, I believe that I look ugly.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "hygiene"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p>Today, I have not noticed any recent changes in my interest in sex.</p><p>Today, I am less interested in sex than I used to be.</p><p>Today, I have almost no interest in sex.</p><p>Today, I have lost interest in sex completely.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "sexdrive"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Today, I have not lost interest in other people.</p><p>Today, I am less interested in other people than I used to be.</p><p>Today, I have lost most of my interest in other people.</p><p>Today, I have lost all of my interest in other people.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "isolated"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Today, I do not feel like a failure.</p><p>Today, I feel I have failed more than the average person.</p><p>Today, when I look back on my life, all I see are failures.</p><p>Today, I feel I am a complete failure as a person.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "guilt"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>Last night, I slept as well as usual.</p><p>Last night, I didn\'t sleep as well as I used to.</p><p>Last night, I slept more than I usually do</p><p>I slept far too long to be considered even remotely healthy. </p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "sleep"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>Today, I am not particularly discouraged about the future.</p><p>Today, I feel discouraged about the future.</p><p>Today, I feel I have nothing to look forward to.</p><p>Today, I feel the future is hopeless and that things cannot improve.</p></body></html>"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "prospects"))
        self.altmans_summary_label.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">How Depo\'d Are You?</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">1-10 :</span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\"> These ups and downs are considered normal </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">11-16 </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">: Mild mood disturbance </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">17-20 </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">: Borderline clinical depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">21-30 : </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">Moderate depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">31-40 : </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">Severe depression </span></p><p><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt; font-weight:600;\">over 40 : </span><span style=\" font-family:\'TimesNewRoman\'; font-size:12pt;\">Extreme depression </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "sum"))
        self.beck_time.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.beck_date.setDisplayFormat(_translate("MainWindow", "yyyy/mm/dd"))
        self.menuBECK.setTitle(_translate("MainWindow", "BECK"))
        self.menuViews.setTitle(_translate("MainWindow", "Views"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionCommit.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionDelete_Record.setText(_translate("MainWindow", "Delete Record"))
        self.actionDelete_Record.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionMinimize.setText(_translate("MainWindow", "Minimize"))
        self.actionMinimize.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionMaximize.setShortcut(_translate("MainWindow", "Alt+M"))
        self.actionInput_View.setText(_translate("MainWindow", "Input View"))
        self.actionInput_View.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionDataview.setText(_translate("MainWindow", "Dataview"))
        self.actionDataview.setShortcut(_translate("MainWindow", "Ctrl+2"))
